article/urls.py
from django.urls import path
from article.views import show_article_page, MakeArticleForm, delete_article, inside_article, edit_article, add_comment, delete_comment

app_name = 'article'

urlpatterns = [
    path('',show_article_page , name='show_article_page'),
    path('create/', MakeArticleForm, name='make_article_form'),
    path('delete/<int:id>/', delete_article, name='delete_article'),
    path('article/<int:id>/', inside_article, name='inside_article'),
    path('edit/<int:id>/', edit_article, name='edit_article'),
    path('<int:article_id>/add_comment/', add_comment, name='add_comment'),
    path('<int:article_id>/delete_comment/<int:comment_index>/', delete_comment, name='delete_comment'),
]

balink/urls.py
from django.contrib import admin
from django.urls import path, include 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('landing_page.urls')),
    path('auth/', include('authentication.urls')),
    path('product/', include('product.urls')),
    path('review/', include('review.urls')),
    path('cart/', include('cart.urls')),
    path('bookmarks/', include('bookmarks.urls')),
    path('article/', include('article.urls'))
]

cart/urls.py
from django.urls import path
from authentication.views import *
from cart.views import *
from django.urls import path, include

app_name = 'cart'

urlpatterns = [
    path("", show_cart, name="show_cart"),
    path('auth/', include('django.contrib.auth.urls')),
    path("history/", show_history, name="show_history"),
    path("add-to-cart/<uuid:product_id>/", add_to_cart, name="add_to_cart"),
    path("remove/<uuid:car_id>", remove_car_from_cart, name="remove"),
    path("remove-car/<uuid:id>", remove_car_from_cart_ajax, name="remove_car_from_cart_ajax"),
    path('booking-cart-ajax/', booking_cart_ajax, name='booking_cart_ajax'),
    path('json/', show_json, name='show_json'),
    path('json/<str:id>/', show_json_by_id, name='show_json_by_id'),
    path('add-to-cart-flutter/<uuid:product_id>/', add_product_to_cart_flutter, name='add_product_to_cart_flutter'),
    path('get-user-cart/', get_user_cart, name='get_user_cart'),
    path('remove-product-from-cart-flutter/', remove_product_from_cart_flutter, name='remove_product_from_cart_flutter'),
    path("get-history/", get_history_flutter, name="get_history_flutter"),
    path('booking-cart-flutter/', booking_cart_flutter, name='booking_cart_flutter'),
]

product/urls.py
from django.urls import path, include
from product.views import show_product_page, show_product_detail, edit_product, add_product, delete_product, show_xml, show_json, show_json_by_id, show_xml_by_id, add_product_flutter, delete_product_flutter, edit_product_flutter

app_name = 'product'

urlpatterns = [
    path('', show_product_page, name='show_product_page'),
    path('detail/<uuid:id>/', show_product_detail, name='show_product_detail'),
    path('edit/<uuid:id>/', edit_product, name='edit_product'),
    path('edit_product_flutter/<uuid:id>', edit_product_flutter, name='edit_product_flutter'), 
    path('add_product/', add_product, name='add_product'),
    path('add_product_flutter/', add_product_flutter, name='add_product_flutter'),
    path('delete_product/<uuid:id>/', delete_product, name='delete_product'),
    path('delete_product_flutter/<uuid:id>/', delete_product_flutter, name='delete_product_flutter'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('xml/<uuid:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<uuid:id>/', show_json_by_id, name='show_json_by_id'),    
]

article/models.py
from django.db import models
from django.contrib.auth.models import User
from product.models import Product
from django.utils import timezone


class Article(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    ride = models.ForeignKey(Product, on_delete=models.CASCADE, null=True, blank=True)  
    title = models.CharField(max_length=200)
    content = models.TextField()
    image = models.URLField()
    comments = models.JSONField(default=list, blank=True)  
    image1 = models.URLField(null=True, blank=True)
    image2 = models.URLField(null=True, blank=True)
    image3 = models.URLField(null=True, blank=True)


    def add_comment(self, user, comment_content):
        """
        Add a comment to the JSON field.
        """
        new_comment = {
            'user': user.username,
            'content': comment_content,
            'timestamp': timezone.now().strftime('%Y-%m-%d %H:%M:%S')
        }
        self.comments.append(new_comment)
        self.save()


    def delete_comment(self, index):
        """
        Delete a comment by its index from the JSON field.
        """
        try:
            self.comments.pop(index)
            self.save()
        except IndexError:
            pass

    def __str__(self):
        return self.title

article/forms.py
from django import forms
from django.forms import ModelForm
from article.models import Article

class ArticleForms(ModelForm):
    class Meta:
        model = Article
        fields = ["title", "content", "image", "image1", "image2", "image3"]
        widgets = {
            'title': forms.TextInput(attrs={
                'class': 'block w-full p-2 border rounded',
                'placeholder': 'Enter article title'
            }),
            'content': forms.Textarea(attrs={
                'class': 'block w-full p-2 border rounded resize-none h-32 overflow-y-auto',
                'placeholder': 'Enter article content'
            }),
            'image': forms.URLInput(attrs={
                'class': 'block w-full p-2 border rounded',
                'placeholder': 'Enter main image URL'
            }),
            'image1': forms.URLInput(attrs={
                'class': 'block w-full p-2 border rounded',
                'placeholder': 'Enter additional image 1 URL'
            }),
            'image2': forms.URLInput(attrs={
                'class': 'block w-full p-2 border rounded',
                'placeholder': 'Enter additional image 2 URL'
            }),
            'image3': forms.URLInput(attrs={
                'class': 'block w-full p-2 border rounded',
                'placeholder': 'Enter additional image 3 URL'
            }),
        }

article/views.py
from django.shortcuts import render, redirect, get_object_or_404  
from article.forms import ArticleForms
from article.models import Article
from product.models import Product
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse, HttpResponse
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST
import json
from authentication.models import UserProfile
from .models import Product



@login_required(login_url='authentication:login')
def show_article_page(request):
    show_article = Article.objects.all()
    current_user = request.user
    user = UserProfile.objects.get(user = current_user)

    other_articles = [
        {"title": "15 Destinasi Instagrammable di Bali ", "url": "https://www.indonesia.travel/id/id/ide-liburan/15-destinasi-instagrammable-di-bali-yang-harus-sobat-pesona-kunjungi.html"},
        {"title": "10 Objek Wisata Terbaik di Bali", "url": "https://www.tripadvisor.co.id/Attractions-g294226-Activities-Bali.html"},
        {"title": "15+ Rekomendasi Tempat Liburan Seru di Pulau Bali", "url": "https://www.cimbniaga.co.id/id/inspirasi/gayahidup/rekomendasi-tempat-wisata-alam-dan-budaya-di-pulau-bali"},
        {"title": "Top 30 Tempat Wisata di Bali yang Tak Boleh Dilewatkan", "url": "https://id.trip.com/guide/activity/tempat-wisata-di-bali.html"},
        {"title": "10 Best Things to Do and More in Bali", "url": "https://www.getyourguide.com/-l347/?cmp=ga&ps_theme=ttd&cq_src=google_ads&cq_cmp=15508255885&cq_con=132581187524&cq_term=bali%20top10&cq_med=&cq_plac=&cq_net=g&cq_pos=&cq_plt=gp&campaign_id=15508255885&adgroup_id=132581187524&target_id=kwd-1432321165848&loc_physical_ms=9072593&match_type=b&ad_id=574899113022&keyword=bali%20top10&ad_position=&feed_item_id=&placement=&device=c&partner_id=CD951&gad_source=1&gbraid=0AAAAADmzJCMfR3TgRU8a7SFt9CREmRFNL&gclid=CjwKCAjwyfe4BhAWEiwAkIL8sLqdQBcLdYQWsDByJsrgU5ib8Sn5VPY7EhAqrD0Fr0XwEVS7lcTo7xoCXgsQAvD_BwE"},
        {"title": "Fun Activities In Bali", "url": "https://www.booking.com/region/id/bali.en.html?aid=377400;label=bali-5VmtKJTi*Vx6LCdfGQXLFAS388490388182:pl:ta:p1:p2:ac:ap:neg:fi:tikwd-308609428065:lp9072593:li:dec:dm:ppccp=UmFuZG9tSVYkc2RlIyh9YdbYVqXDN8zp7PNDFvT66M8;ws=&gbraid=0AAAAAD_Ls1JX1u4e669AzBLVbhxfozgwr&gclid=CjwKCAjwyfe4BhAWEiwAkIL8sGlIzFJWfwqJFv9X1GKTiXl14W24xGclMXaIQ12MsVlM7i3DEzVZ-xoCUXAQAvD_BwE"}
    ]

    context = {
        'show_article': show_article,
        'other_articles': other_articles,  
        'user': user,
    }

    return render(request, "article_page.html", context)



@login_required(login_url='authentication:login')
def MakeArticleForm(request):
    if request.method == 'POST':
        form = ArticleForms(request.POST)
        if form.is_valid():
            article = form.save(commit=False) 
            article.user = request.user      
            article.save()                   
            return redirect('article:show_article_page')    
    else:
        form = ArticleForms()
    return render(request, 'make_article_forms.html', {'form': form})



@login_required(login_url='authentication:login')
def delete_article(request, id):
    article = get_object_or_404(Article, id=id)
    if request.method == "POST":
        article.delete()
        return redirect('article:show_article_page')
    return redirect('article:show_article_page')



@login_required(login_url='authentication:login')
def inside_article(request, id):
    article = get_object_or_404(Article, id=id)
    product = Product.objects.all()[:3]
    paragraphs = article.content.split('\n\n')
    current_user = request.user  
    user_profile = UserProfile.objects.get(user=current_user)

    context = {
        'article': article,
        'paragraphs': paragraphs, 
        'comments': article.comments,  
        'products': product,
        'user': user_profile
    }
    return render(request, "inside_article.html", context)



@login_required(login_url='authentication:login')
@csrf_exempt  
@require_POST
def add_comment(request, article_id):
    try:
        comment_text = request.POST.get('comment_text', '').strip()
        
        if comment_text:
            article = get_object_or_404(Article, id=article_id)
            article.add_comment(request.user, comment_text)
            
            return JsonResponse({'success': True, 'user': request.user.username, 'comment': comment_text})
        else:
            return JsonResponse({'success': False, 'error': 'Empty comment text'})
    
    except Exception as e:
        return JsonResponse({'success': False, 'error': str(e)})

    return JsonResponse({'success': False, 'error': 'Invalid request method'})



@login_required(login_url='authentication:login')
@csrf_exempt  # Allow CSRF exemption for the view
def delete_comment(request, article_id, comment_index):
    article = get_object_or_404(Article, id=article_id)
    
    # Check if the user is authorized to delete the comment
    if article.user != request.user and not request.user.userprofile.privilege == "admin":
        return JsonResponse({'success': False, 'error': 'Not authorized'}, status=403)
    
    if request.method == "POST":
        try:
            article.delete_comment(comment_index)  # Remove the comment at the specified index
            return JsonResponse({'success': True})
        except IndexError:
            return JsonResponse({'success': False, 'error': 'Invalid comment index'}, status=400)
    
    return JsonResponse({'success': False, 'error': 'Invalid request method'}, status=405)



@login_required(login_url='authentication:login')
def edit_article(request, id):
    article = get_object_or_404(Article, id=id)

    if request.method == 'POST':
        form = ArticleForms(request.POST, instance=article)
        if form.is_valid():
            form.save()
            return redirect('article:show_article_page')
    else:
        form = ArticleForms(instance=article)

    return render(request, 'edit_article_form.html', {'form': form, 'article': article})

article/templates/article_page.html
{% extends 'base.html' %} {% load static %} {% block content %} {% include 'navbar.html' %}

<title>Balink | Place to Go</title>
<div class="container mx-auto mt-8">
    <!-- Main Header with Title -->
    <div class="mb-8">
        <h1 class="text-3xl font-medium text-gray-800 tracking-tight">Explore Our Latest Articles</h1>
    </div>

    <div class="flex flex-col lg:flex-row gap-6">
        <!-- Main Articles Section -->
        <div class="w-full lg:w-3/4">
            <div class="space-y-6">
                {% for article in show_article %}
                    <div class="block bg-white rounded-md border border-gray-300 overflow-hidden shadow-md hover:shadow-lg transition-shadow duration-300 transform hover:-translate-y-1 no-underline">
                        <a href="{% url 'article:inside_article' article.id %}" class="w-full">
                            <div class="w-full h-40 overflow-hidden">
                                <img src="{{ article.image }}" alt="{{ article.title }}" class="w-full h-full object-cover transition-transform duration-500 transform hover:scale-105">
                            </div>
                            <div class="p-4 bg-white">
                                <h2 class="text-xl font-semibold mb-1 text-gray-900">{{ article.title }}</h2>
                                <p class="text-gray-700 mb-2">
                                    {{ article.content|slice:":100" }}{% if article.content|length > 100 %}... <span class="text-blue-500">View More</span>{% endif %}
                                </p>
                            </div>
                        </a>
                        {% if user.privilege == "admin" %}
                            <div class="flex justify-end items-center mt-2 space-x-2 bg-white mb-5 mr-5">
                                <!-- Edit Button -->
                                <a href="{% url 'article:edit_article' article.id %}" class="text-white bg-yellow-500 px-4 py-2 rounded hover:bg-yellow-600 transition duration-300 text-sm font-medium">Edit</a>
                                <!-- Delete Button -->
                                <form action="{% url 'article:delete_article' article.id %}" method="post" class="inline-block">
                                    {% csrf_token %}
                                    <button type="submit" class="text-white bg-red-500 px-4 py-2 rounded-md hover:bg-red-600 transition duration-300 text-sm font-medium">Delete</button>
                                </form>
                            </div>
                        {% endif %}
                    </div>
                {% endfor %}
            </div>
        </div>
        

        <!-- Other Articles and Map Section -->
        <div class="w-full lg:w-1/4 space-y-4">
            {% if user.privilege == "admin" %}
                <a href="{% url 'article:make_article_form' %}" class="block text-white bg-green-600 px-4 py-2 rounded-md hover:bg-green-700 transition duration-300 text-center">Add New Article</a>
            {% endif %}
            <div class="bg-blue-600 text-white shadow-md rounded-md p-4 mt-4">
                <h2 class="text-lg font-semibold mb-4">Other Articles</h2>
                <div class="flex flex-col space-y-2">
                    {% for other in other_articles %}
                        <a href="{{ other.url }}" class="block bg-blue-400 p-2 rounded-md hover:bg-blue-300 transition duration-300 text-sm text-white">
                            {{ other.title }}
                        </a>
                    {% endfor %}
                </div>
            </div>

            <!-- Map Section -->
            <div class="bg-blue-600 text-white shadow-md rounded-md p-4">
                <h2 class="text-lg font-semibold mb-4">Find Us on Google Maps</h2>
                <div class="flex flex-col space-y-2">
                    <!-- Embedded Google Map -->
                    <iframe 
                        src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d126762.6833927802!2d115.10977737748834!3d-8.340538689772307!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x2dd22aa31f21bf97%3A0x3030bfbca7b9b30!2sBali!5e0!3m2!1sen!2sid!4v1634814933983!5m2!1sen!2sid" 
                        width="100%" height="200" style="border:0;" allowfullscreen="" loading="lazy">
                    </iframe>
                    <!-- Link to Google Maps -->
                    <a href="https://goo.gl/maps/ZRjU4DUuRcs4AStT6" target="_blank" class="text-white hover:underline mt-2">Open in Google Maps</a>
                </div>
            </div>
        </div>
    </div>

    <!-- Fun Fact Section -->
    <div class="mt-12 bg-blue-100 py-8 px-4 rounded-md text-center">
        <h2 class="text-2xl font-semibold text-gray-800 mb-4">Did You Know?</h2>
        <p class="text-gray-600 text-lg italic">
            "Bali isn’t just an island, it’s a gateway to countless adventures and cultural treasures.  At BaLink, we believe every journey through Bali unveils a new story waiting to be discovered."
        </p>
    </div>
</div>

{% endblock content %}

article/templates/edit_article_form.html
{% extends 'base.html' %} {% load static %} {% block content %} {% include 'navbar.html' %}


<title>Balink | Edit Article</title>
<div class="container mx-auto mt-8">
    <h1 class="text-2xl font-medium text-gray-800 mb-4">Edit Article: {{ article.title }}</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="bg-blue-600 text-white px-4 py-2 rounded hover:bg-blue-700 transition duration-300">Save Changes</button>
    </form>
</div>
{% endblock content %}

article/templates/inside_article.html
{% extends 'base.html' %} {% load static %} {% block content %} {% include 'navbar.html' %}

<title>Balink | Inside Article</title>
<div class="container mx-auto mt-8">
    <!-- Display Article Details -->
    <div class="bg-white p-6 rounded-md mb-8 w-full">
        <h1 class="text-3xl font-bold mb-4 text-gray-800">{{ article.title }}</h1>

        <!-- Slideshow Section -->
        <div class="relative w-full h-[600px] mb-4 overflow-hidden rounded-md">
            <div id="slideshow" class="relative w-full h-full">
                <img src="{{ article.image }}" alt="{{ article.title }}" class="w-full h-full object-cover absolute transition-opacity duration-500 opacity-100">
                <img src="{{ article.image1 }}" alt="{{ article.title }}" class="w-full h-full object-cover absolute transition-opacity duration-500 opacity-0">
                <img src="{{ article.image2 }}" alt="{{ article.title }}" class="w-full h-full object-cover absolute transition-opacity duration-500 opacity-0">
                <img src="{{ article.image3 }}" alt="{{ article.title }}" class="w-full h-full object-cover absolute transition-opacity duration-500 opacity-0">
            </div>
            
            <!-- Navigation Buttons -->
            <button id="prevBtn" class="absolute top-1/2 left-4 bg-gray-800 text-white bg-opacity-50 hover:bg-opacity-100 px-3 py-1 rounded-full transform -translate-y-1/2">&lt;</button>
            <button id="nextBtn" class="absolute top-1/2 right-4 bg-gray-800 text-white bg-opacity-50 hover:bg-opacity-100 px-3 py-1 rounded-full transform -translate-y-1/2">&gt;</button>
            
            <!-- Indicator Dots -->
            <div id="dotsContainer" class="absolute bottom-4 left-1/2 transform -translate-x-1/2 flex space-x-1">
                <span class="dot w-2 h-2 bg-gray-300 rounded-full"></span>
                <span class="dot w-2 h-2 bg-gray-300 rounded-full"></span>
                <span class="dot w-2 h-2 bg-gray-300 rounded-full"></span>
                <span class="dot w-2 h-2 bg-gray-300 rounded-full"></span>
            </div>
        </div>
        
        <br>
        <!-- Display Article Content -->
        {% for paragraph in paragraphs %}
        <p class="text-gray-600 text-lg leading-relaxed mb-4 break-words whitespace-normal" style="line-height: 1.8; text-align: justify;">
            {{ paragraph }}
        </p>
        {% endfor %}

    </div>

    <!-- Section for Comments -->
    <div class="mt-8">
        <h2 class="text-2xl font-semibold mb-4">Comments</h2>
        <div id="comments-section">
            {% for comment in article.comments %}
                <div class="bg-gray-100 p-4 rounded-md mb-2">
                    <p class="font-semibold">{{ comment.user }}</p>
                    <p>{{ comment.content }}</p>
                    <p class="text-gray-400 text-sm">{{ comment.timestamp }}</p>
                    
                    <!-- Only show the delete button if the user is an admin -->
                    {% if user.privilege == "admin" %}
                    <form action="{% url 'article:delete_comment' article.id forloop.counter0 %}" method="post" class="mt-2">
                        {% csrf_token %}
                        <button type="submit" class="text-red-500 hover:text-red-700">Delete</button>
                    </form>
                    {% endif %}
                </div>
            {% empty %}
                <p class="text-gray-600">No comments yet. Be the first to comment!</p>
            {% endfor %}
        </div>

        <!-- Add Comment Button Section -->
        <div class="mt-4">
            <button id="addCommentBtn" class="bg-blue-500 text-white px-4 py-2 rounded hover:bg-blue-600">Add Comment</button>
        </div>
    </div>


    <!-- Product Cards Section -->
    <div class="mt-12">
        <h2 class="text-2xl font-semibold mb-4">Our Top 3 Recommendation Cars</h2>
        <div class="flex justify-between space-x-4">
            {% for product in products %}
                <div class="bg-white border rounded-md shadow-sm w-1/3">
                    <img src="{{ product.image_url }}" alt="{{ product.name }}" class="w-full h-32 object-cover rounded-t-md">
                    <div class="p-4">
                        <h3 class="text-lg font-semibold">{{ product.name }}</h3>
                        <p class="text-gray-600 mb-2">Price: ${{ product.price }}</p>
                        <a href="{% url 'product:show_product_detail' product.id %}" class="text-blue-600 hover:text-blue-800">View Details</a>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
</div>

<!-- Comment Modal -->
<div id="commentModal" class="hidden fixed inset-0 bg-gray-800 bg-opacity-75 flex items-center justify-center">
    <div class="bg-white p-6 rounded-md shadow-md w-96">
        <h3 class="text-xl font-bold mb-4">Write Your Comment</h3>
        <form id="commentForm">
            <textarea id="commentText" name="comment_text" class="w-full p-3 border rounded mb-4 h-40 resize-none focus:ring focus:ring-blue-300" placeholder="Write your comment..."></textarea>
            <button type="submit" class="bg-blue-500 text-white px-4 py-2 rounded hover:bg-blue-600">Submit</button>
            <button type="button" id="closeModalBtn" class="bg-gray-500 text-white px-4 py-2 rounded ml-2 hover:bg-gray-600">Close</button>
        </form>
    </div>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script>
    // Handle the display of the modal for adding comments
    document.getElementById("addCommentBtn").addEventListener("click", function() {
        document.getElementById("commentModal").classList.remove("hidden");
    });

    document.getElementById("closeModalBtn").addEventListener("click", function() {
        document.getElementById("commentModal").classList.add("hidden");
    });

    // Adding an event listener to the form for AJAX submission
    document.getElementById("commentForm").addEventListener("submit", function(e) {
        e.preventDefault();
        addComment();
    });

    function addComment() {
        const formData = new FormData(document.getElementById("commentForm"));
        const articleId = "{{ article.id }}";

        fetch(`/article/${articleId}/add_comment/`, {
            method: "POST",
            headers: {
                "X-CSRFToken": "{{ csrf_token }}",  // Include CSRF token
            },
            body: formData,
        })
        .then(response => response.json())
        .then(data => {
            if (data.success) {
                // Construct the HTML for the new comment
                const newComment = `
                    <div class="bg-gray-100 p-4 rounded-md mb-2 animate-slide-in">
                        <p class="font-semibold">${data.user}</p>
                        <p>${data.comment}</p>
                        <p class="text-gray-400 text-sm">Just now</p>
                    </div>
                `;
                // Insert the new comment into the comments section
                document.getElementById("comments-section").insertAdjacentHTML('beforeend', newComment);
                // Hide the modal and reset the textarea
                document.getElementById("commentModal").classList.add("hidden");
                document.getElementById("commentForm").reset();
            } else {
                alert("Failed to add comment: " + data.error);
            }
        })
        .catch(error => {
            console.error("Error:", error);
        });
    }

    // JavaScript for slideshow navigation
    let currentSlide = 0;
    const slides = document.querySelectorAll("#slideshow img");
    const dots = document.querySelectorAll("#dotsContainer .dot");
    let slideInterval;

    function updateSlides() {
        slides.forEach((slide, index) => {
            slide.style.opacity = index === currentSlide ? "1" : "0";
            dots[index].classList.toggle("bg-gray-800", index === currentSlide);
            dots[index].classList.toggle("bg-gray-300", index !== currentSlide);
        });
    }

    function showNextSlide() {
        currentSlide = (currentSlide + 1) % slides.length;
        updateSlides();
    }

    function resetSlideInterval() {
        clearInterval(slideInterval);
        slideInterval = setInterval(showNextSlide, 5000); // Restart the timer to 5 seconds
    }

    document.getElementById("nextBtn").addEventListener("click", function() {
        showNextSlide();
        resetSlideInterval();  // Reset the interval when clicking the next button
    });

    document.getElementById("prevBtn").addEventListener("click", function() {
        currentSlide = (currentSlide - 1 + slides.length) % slides.length;
        updateSlides();
        resetSlideInterval();  // Reset the interval when clicking the prev button
    });

    // Initial update to show the first slide
    updateSlides();

    // Automatically change slides every 5 seconds
    slideInterval = setInterval(showNextSlide, 5000);  // 5000 milliseconds = 5 seconds
</script>

{% endblock content %}

article/templates/make_article_forms.html
{% extends 'base.html' %} {% load static %} {% block content %} {% include 'navbar.html' %}


<title>Balink | Make Article</title>
<div class="container mx-auto p-4 flex justify-center items-center min-h-screen bg-gray-200">
    <form method="post" class="w-full max-w-lg bg-white p-8 rounded-lg shadow-lg">
        {% csrf_token %}

        <div class="mb-6">
            <label for="id_title" class="block text-gray-600 font-semibold mb-2 flex items-center">
                <i class="far fa-user mr-2"></i> Article Title
            </label>  
            {{ form.title }}
        </div>

        <div class="mb-6">
            <label for="id_content" class="block text-gray-600 font-semibold mb-2 flex items-center">
                <i class="far fa-edit mr-2"></i> Content
            </label>
            {{ form.content }}
        </div>

        <div class="mb-6">
            <label for="id_image" class="block text-gray-600 font-semibold mb-2 flex items-center">
                <i class="far fa-image mr-2"></i> Main Image (URL)
            </label>
            {{ form.image }}
        </div>

        <div class="mb-6">
            <label for="id_image1" class="block text-gray-600 font-semibold mb-2 flex items-center">
                <i class="far fa-image mr-2"></i> Additional Image 1 (URL)
            </label>
            {{ form.image1 }}
        </div>

        <div class="mb-6">
            <label for="id_image2" class="block text-gray-600 font-semibold mb-2 flex items-center">
                <i class="far fa-image mr-2"></i> Additional Image 2 (URL)
            </label>
            {{ form.image2 }}
        </div>

        <div class="mb-6">
            <label for="id_image3" class="block text-gray-600 font-semibold mb-2 flex items-center">
                <i class="far fa-image mr-2"></i> Additional Image 3 (URL)
            </label>
            {{ form.image3 }}
        </div>

        <div class="text-right">
            <button type="submit" class="bg-blue-600 text-white font-bold py-2 px-4 rounded-lg hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-blue-600">
                Save Articles
            </button>
        </div>
    </form>
</div>


{% endblock content %}