balink/urls.py
from django.contrib import admin
from django.urls import path, include 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('landing_page.urls')),
    path('auth/', include('authentication.urls')),
    path('product/', include('product.urls')),
    path('review/', include('review.urls')),
    path('cart/', include('cart.urls')),
    path('bookmarks/', include('bookmarks.urls')),
    path('article/', include('article.urls'))
]

cart/urls.py
from django.urls import path
from authentication.views import *
from cart.views import *
from django.urls import path, include

app_name = 'cart'

urlpatterns = [
    path("", show_cart, name="show_cart"),
    path('auth/', include('django.contrib.auth.urls')),
    path("history/", show_history, name="show_history"),
    path("add-to-cart/<uuid:product_id>/", add_to_cart, name="add_to_cart"),
    path("remove/<uuid:car_id>", remove_car_from_cart, name="remove"),
    path("remove-car/<uuid:id>", remove_car_from_cart_ajax, name="remove_car_from_cart_ajax"),
    path('booking-cart-ajax/', booking_cart_ajax, name='booking_cart_ajax'),
    path('json/', show_json, name='show_json'),
    path('json/<str:id>/', show_json_by_id, name='show_json_by_id'),
    path('add-to-cart-flutter/<uuid:product_id>/', add_product_to_cart_flutter, name='add_product_to_cart_flutter'),
    path('get-user-cart/', get_user_cart, name='get_user_cart'),
    path('remove-product-from-cart-flutter/', remove_product_from_cart_flutter, name='remove_product_from_cart_flutter'),
    path("get-history/", get_history_flutter, name="get_history_flutter"),
    path('booking-cart-flutter/', booking_cart_flutter, name='booking_cart_flutter'),
]

product/urls.py
from django.urls import path, include
from product.views import show_product_page, show_product_detail, edit_product, add_product, delete_product, show_xml, show_json, show_json_by_id, show_xml_by_id, add_product_flutter, delete_product_flutter, edit_product_flutter

app_name = 'product'

urlpatterns = [
    path('', show_product_page, name='show_product_page'),
    path('detail/<uuid:id>/', show_product_detail, name='show_product_detail'),
    path('edit/<uuid:id>/', edit_product, name='edit_product'),
    path('edit_product_flutter/<uuid:id>', edit_product_flutter, name='edit_product_flutter'), 
    path('add_product/', add_product, name='add_product'),
    path('add_product_flutter/', add_product_flutter, name='add_product_flutter'),
    path('delete_product/<uuid:id>/', delete_product, name='delete_product'),
    path('delete_product_flutter/<uuid:id>/', delete_product_flutter, name='delete_product_flutter'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('xml/<uuid:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<uuid:id>/', show_json_by_id, name='show_json_by_id'),    
]

review/urls.py
from django.urls import path
from review.views import show_main, ride_to_review, add_review_entry_ajax, delete_review
from review.views import show_json, show_json_by_id
from review.views import add_review_flutter, all_reviews_flutter, all_rides_flutter, delete_review_flutter, edit_review_flutter, user_review_flutter
app_name = 'review'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('ride-to-review', ride_to_review, name='ride_to_review'),
    path('json/', show_json, name='show_json'),
    path('json/<int:id>/', show_json_by_id, name='show_json_by_id'),
    path('add-review-entry-ajax', add_review_entry_ajax, name='add_review_entry_ajax'),
    path('delete-review/<int:review_id>/', delete_review, name='delete_review'),
    path('add-review-flutter/', add_review_flutter, name='add_review_flutter'),
    path('edit-review-flutter/', edit_review_flutter, name='edit_review_flutter'),
    path('user-review-flutter/', user_review_flutter, name='user_review_flutter'),
    path('all-reviews-flutter/', all_reviews_flutter, name='all_reviews_flutter'),
    path('all-rides-flutter/', all_rides_flutter, name='all_rides_flutter'),
    path('delete-review-flutter/<int:review_id>/', delete_review_flutter, name='delete_review_flutter'),
]

review/models.py
from django.db import models
from django.contrib.auth.models import User
from product.models import Product
from django.core.validators import MinValueValidator, MaxValueValidator

# Create your models here.
class Review(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    ride = models.ForeignKey(Product, on_delete=models.CASCADE)
    rating = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(5)])
    review_message = models.TextField()

review/forms.py
from django.forms import ModelForm
from review.models import Review
from django.utils.html import strip_tags

class ReviewEntryForm(ModelForm):
    class Meta:
        model = Review
        fields = ["rating", "review_message"]

    def clean_review_message(self):
        review_message = self.cleaned_data["review_message"]
        return strip_tags(review_message)

review/views.py
import json
import uuid
from django.urls import reverse
from product.models import Product
from review.models import Review
from review.forms import ReviewEntryForm
from django.http import HttpResponse, JsonResponse
from django.core import serializers
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, render, redirect
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST
from django.utils.html import strip_tags
from django.db.models import Q

# Create your views here.
# Method untuk show all reviews page
@login_required(login_url="authentication:login")
def show_main(request):
    rating_filter = request.GET.get('rating')
    if rating_filter:
        reviews = Review.objects.filter(rating=rating_filter).order_by('-id')
    else:
        reviews = Review.objects.all().order_by('-id')

    user = request.user
    context = {
        'user': user,
        'reviews': reviews,
    }
    return render(request, "review.html", context)

# Method untuk show all rides to review
@login_required(login_url="authentication:login")
def ride_to_review(request):
    search_key = request.GET.get('search', '')
    
    if search_key:
        rides = Product.objects.filter(name__icontains=search_key)
    else:
        rides = Product.objects.all()
    
    form = ReviewEntryForm(request.POST or None)
    context = {
        'products': rides,
        'form': form,
    }

    return render(request, "ride_to_review.html", context)

# Method untuk ajax add review
@csrf_exempt
@require_POST
def add_review_entry_ajax(request):
    user = request.user
    ride = get_object_or_404(Product, id=request.POST.get("product_id"))
    rating = request.POST.get("rating")
    review_message = strip_tags(request.POST.get("review_message"))

    if rating and review_message:
        new_review = Review(
            user=user,
            ride=ride,
            rating=rating,
            review_message=review_message,
        )
        new_review.save()
        
        return redirect(reverse('review:show_main'))

    return render(request, 'review_form.html', {
        'error_message': "Invalid input. Please fill all fields.",
    })

# Method untuk delete review for admin
@login_required(login_url="authentication:login")
def delete_review(request, review_id):
    review = get_object_or_404(Review, id=review_id)
    
    if request.user.userprofile.privilege == "admin":
        review.delete()
    
    return redirect('review:show_main')

# Method untuk add review in flutter
@csrf_exempt
@login_required
def add_review_flutter(request):
    if request.method == 'POST':

        data = json.loads(request.body)
        id = uuid.UUID(data["id"])
        ride = Product.objects.get(id=data["id"])

        new_review = Review.objects.create(
            user=request.user,
            ride=ride,
            rating=int(data["rating"]),
            review_message=data["review_message"] 
        )

        new_review.save()

        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)

# Method edit review di flutter
@csrf_exempt
@login_required
def edit_review_flutter(request):
    if request.method == 'POST':
        data = json.loads(request.body)
        review_id = data["id"]
        rating = int(data["rating"])
        review_message = data["review_message"]

        try:
            review = Review.objects.get(id=review_id, user=request.user)
        except Review.DoesNotExist:
            return JsonResponse({"status": "error", "message": "Review not found or you don't have permission to edit it"}, status=400)

        review.rating = rating
        review.review_message = review_message

        review.save()
        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error", "message": "Invalid request method"}, status=401)

# Method untuk data json all reviews di flutter
@login_required
def all_reviews_flutter(request):
    reviews = Review.objects.all().order_by('-id')

    list_review = []
    for review in reviews:
        review_data = {
            "id": str(review.id),
            "image": review.ride.image_url,
            "username": review.user.username,
            "rideName": review.ride.name,
            "rating": review.rating,
            "reviewMessage": review.review_message,
        }

        list_review.append(review_data)
        
    return HttpResponse(json.dumps(list_review), content_type="application/json")

@login_required
def user_review_flutter(request):
    user_reviews = Review.objects.filter(user=request.user).order_by('-id')

    list_user_review = []
    for review in user_reviews:
        review_data = {
            "id": str(review.id),
            "image": review.ride.image_url,
            "username": review.user.username,
            "rideName": review.ride.name,
            "rating": review.rating,
            "reviewMessage": review.review_message,
        }

        list_user_review.append(review_data)

    return HttpResponse(json.dumps(list_user_review), content_type="application/json")

# Method untuk data json all rides to review di flutter
@login_required
def all_rides_flutter(request):
    list_ride = []
    rides = Product.objects.all().order_by('-id')

    for ride in rides:
        ride_data = {
            "id": str(ride.id),
            "image": ride.image_url,
            "rideName": ride.name,
        }

        list_ride.append(ride_data)
    return HttpResponse(json.dumps(list_ride), content_type="application/json")

# Method untuk delete review for admin di flutter
@login_required
@csrf_exempt
def delete_review_flutter(request, review_id):
    if request.user.userprofile.privilege != "admin":
        return JsonResponse({'status': 'error', 'message': 'You do not have permission'}, status=403)

    review = get_object_or_404(Review, id=review_id)
    review.delete()
    return JsonResponse({'status': 'success', 'message': 'Review deleted successfully'})

def show_json(request):
    data = Review.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_json_by_id(request, id):
    data = Review.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

review/templates/review.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>BaLink | Review Page</title>
{% endblock meta %}

{% block content %}
{% include 'navbar.html' %}

<!-- Header halaman main review -->
{% if user.is_authenticated and user.userprofile.privilege == "customer" %}
<div class="container mx-auto mt-6 px-4">
  <div class="w-full flex flex-col sm:flex-row items-center sm:justify-between bg-gradient-to-br from-blue-600 to-blue-700 text-white rounded-lg p-6">
      <div class="relative w-full sm:w-1/6 flex-shrink-0 sm:ml-6">
          <img src="{% static 'img/review_header.png' %}" alt="Review rides" class="w-full h-auto object-cover rounded-xl transform hover:scale-110 transition duration-300 ease-in-out" />
      </div>
      <div class="mb-4 sm:mb-0">
          <h2 class="text-4xl md:text-5xl font-bold tracking-tight mb-4 leading-tight">Share your Ride Experience!</h2>
          <p class="text-gray-100 mb-6 leading-relaxed">Share your driving experience in Denpasar! Let others know how BaLink made your trip to dream destinations easier.</p>
          <a href="{% url 'review:ride_to_review' %}" class="bg-yellow-500 hover:bg-yellow-600 text-gray-900 px-6 py-3 rounded-lg font-bold shadow-lg transition-transform transform hover:scale-110">Add Review</a>
      </div>
  </div>
{% endif %}
  
  <!-- Filter buttons -->
  <div class="mt-6 flex justify-center space-x-2">
    <a href="?" class="bg-gray-200 hover:bg-blue-300 text-black px-4 py-2 rounded-xl font-semibold shadow transition duration-300 hover:border-2 hover:border-blue-400">
        All
    </a>
    {% for rating in "12345" %}
    <a href="?rating={{ rating }}" class="bg-gray-200 hover:bg-blue-300 text-black px-5 py-2 rounded-xl font-semibold shadow transition duration-300 hover:border-2 hover:border-blue-400">
        ⭐ {{ rating }}
    </a>
    {% endfor %}
  </div>
</div>

<!-- All review -->
<div class="container mx-auto mt-6 px-4">
    {% if reviews %}
    <div class="review-list grid grid-cols-2 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
        {% for review in reviews %}
        <div class="review-card bg-white rounded-lg shadow-md overflow-hidden hover:shadow-xl flex flex-col relative">
            <a href="{% url 'product:show_product_detail' review.ride.id %}" class="absolute inset-0 z-20"></a>
            
            <div class="relative z-10">
                <img src="{{ review.ride.image_url }}" alt="{{ review.ride.name }}" class="w-full h-36 object-cover" />
                <div class="absolute top-4 right-4 bg-white text-gray-900 px-3 py-1 rounded-full font-bold text-x shadow">
                    ⭐ {{ review.rating }}
                </div>                
            </div>
            <div class="review-info p-4 flex-grow text-left z-10">
                <h2 class="review-name text-1xl font-bold">{{ review.ride.name }}</h2>
                <p class="text-gray-500 text-x leading-relaxed">{{ review.review_message }}</p>
            </div>
            <p class="text-sm text-gray-400 p-4 z-10">Reviewed by {{ review.user.username }}</p>

            <!-- Kalau admin bisa delete -->
            {% if user.is_authenticated and user.userprofile.privilege == "admin" %}
            <form action="{% url 'review:delete_review' review.id %}" method="post" class="absolute bottom-4 right-4 z-30">
                {% csrf_token %}
                <button type="submit" class="bg-blue-600 hover:bg-blue-700 text-white rounded-full p-1.5 transition duration-300 shadow-md">
                    <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" viewBox="0 0 20 20" fill="currentColor">
                        <path fill-rule="evenodd" d="M9 2a1 1 0 00-.894.553L7.382 4H4a1 1 0 000 2v10a2 2 0 002 2h8a2 2 0 002-2V6a1 1 0 100-2h-3.382l-.724-1.447A1 1 0 0011 2H9zM7 8a1 1 0 012 0v6a1 1 0 11-2 0V8zm5-1a1 1 0 00-1 1v6a1 1 0 102 0V8a1 1 0 00-1-1z" clip-rule="evenodd" />
                    </svg>
                </button>
            </form>
            {% endif %}
        </div>
        {% endfor %}
    </div>
    {% else %}
    <div class="flex flex-col items-center justify-center min-h-[24rem] p-6">
        <img src="{% static 'img/no_review_here.png' %}" alt="Sad face" class="w-48 mb-4"/>
        <p class="text-center text-gray-600 mt-4">No review here</p>
    </div>
    {% endif %}
</div>
{% endblock content %}

review/templates/ride_to_review.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>BaLink | Review Page</title>
{% endblock meta %}

{% block content %}
{% include 'navbar.html' %}

<!-- Header halaman ride to review -->
<div class="container mx-auto mt-6 px-4">
    <div class="w-full flex flex-col sm:flex-row items-center sm:justify-center bg-gradient-to-br from-blue-600 to-blue-700 text-white rounded-lg p-6">
        <div class="mb-4 sm:mb-0">
            <h2 class="text-4xl md:text-3xl font-bold leading-tight">Choose your ride to review!</h2>
        </div>
    </div>
</div>

<!-- Search bar -->
<div class="container mx-auto mt-4 px-4">
    <form method="GET" action="{% url 'review:ride_to_review' %}" class="flex items-center space-x-4">
        <input
            type="text"
            name="search"
            placeholder="Search your ride to review"
            class="flex-grow border border-gray-300 bg-gray-200 text-black placeholder-gray-500 rounded-lg p-2 focus:outline-none focus:ring-2 focus:ring-blue-600 focus:bg-white transition"
            value="{{ request.GET.search|default:'' }}"
        />
        <button
            type="submit"
            class="bg-blue-600 hover:bg-blue-700 text-white px-4 py-2 rounded-lg font-bold shadow transition">
            Search
        </button>
    </form>
</div>

<!-- All rides -->
<div class="container mx-auto mt-6 px-4">
    <div class="product-list grid grid-cols-2 sm:grid-cols-3 md:grid-cols-3 lg:grid-cols-4 gap-6" id="product-list">
        {% for product in products %}
        <div class="product-card bg-white rounded-lg shadow-md overflow-hidden hover:shadow-xl flex flex-col">
            <img src="{{ product.image_url }}" alt="{{ product.name }}" class="product-image w-full h-36 object-cover" />
            <div class="product-info p-4 text-center">
                <h2 class="product-name text-1xl font-semibold">{{ product.name }}</h2>
            </div>
            <div class="card-footer p-4 mt-auto flex justify-center">
                <button 
                    data-product-id="{{ product.id }}" 
                    data-product-name="{{ product.name }}" 
                    data-product-image="{{ product.image_url }}" 
                    class="rent-button bg-blue-600 text-white px-4 py-2 rounded-lg hover:bg-blue-700 transition" 
                    onclick="showModal(this);">
                    Review this Ride!
                </button>
            </div>

            <!-- Modal untuk review -->
            <div id="crudModal" tabindex="-1" aria-hidden="true" class="hidden fixed inset-0 z-40 w-full flex items-center justify-center bg-gray-800 bg-opacity-50 overflow-x-hidden overflow-y-auto transition-opacity duration-300 ease-out">
                <div id="crudModalContent" class="relative bg-white rounded-lg shadow-lg w-5/6 sm:w-3/4 md:w-1/2 lg:w-1/3 mx-4 sm:mx-0 transform scale-95 opacity-0 transition-transform transition-opacity duration-300 ease-out p-6 overflow-auto max-h-[90vh]">
                    <!-- Modal header -->
                    <div class="flex items-center justify-between p-4 border-b rounded-t">
                        <h3 class="text-xl font-semibold text-gray-900">
                            Review
                        </h3>
                        <button type="button" class="text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm p-1.5 ml-auto inline-flex items-center" id="closeModalBtn">
                            <svg aria-hidden="true" class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                                <path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path>
                            </svg>
                            <span class="sr-only">Close modal</span>
                        </button>
                    </div>
                    <!-- Modal body -->
                    <div class="px-6 py-4 space-y-6 form-style">
                        <img src="" alt="" class="product-image w-full h-48 object-cover" />
                        <div class="product-info p-4 text-center">
                            <h2 class="product-name text-2xl font-semibold"></h2>
                        </div>
                        <form id="ReviewEntryForm">
                            {% csrf_token %}
                            <input type="hidden" id="product-id" name="product_id">
                            <div class="mb-4">
                                <label for="rating" class="block text-sm font-medium text-gray-700">Rate</label>
                                <input type="number" id="rating" name="rating" min="1" max="5" class="mt-1 block w-full border border-gray-300 rounded-md p-2 hover:border-indigo-700" required>
                            </div>
                            <div class="mb-4">
                                <label for="review_message" class="block text-sm font-medium text-gray-700">Review</label>
                                <textarea id="review_message" name="review_message" rows="3" class="mt-1 block w-full h-52 resize-none border border-gray-300 rounded-md p-2 hover:border-indigo-700" placeholder="Describe your experience!" required></textarea>
                            </div>
                        </form>
                    </div>
                    <!-- Modal footer -->
                    <div class="flex flex-col space-y-2 md:flex-row md:space-y-0 md:space-x-2 p-6 border-t border-gray-200 rounded-b justify-center">
                        <button type="submit" id="submitReviewEntry" form="ReviewEntryForm" class="bg-yellow-400 hover:bg-yellow-500 text-white font-bold py-2 px-4 rounded-lg">Confirm</button>
                        <button type="button" class="bg-blue-600 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-lg" id="cancelButton">Back</button>
                    </div>
                </div>
            </div>
        </div>
        {% empty %}
        <p class="text-gray-600">No products available to review at this time.</p>
        {% endfor %}
    </div>

    <!-- Script untuk AJAX dan modal -->
    <script>
        function showModal(button) {
            const productId = button.getAttribute('data-product-id');
            const productName = button.getAttribute('data-product-name');
            const productImage = button.getAttribute('data-product-image');
    
            document.querySelector('#crudModal .product-name').textContent = productName;
            document.querySelector('#crudModal .product-image').setAttribute('src', productImage);
            document.querySelector('#crudModal .product-image').setAttribute('alt', productName);
            document.querySelector('#product-id').value = productId;
    
            const modal = document.getElementById('crudModal');
            const modalContent = document.getElementById('crudModalContent');
    
            modal.classList.remove('hidden');
            setTimeout(() => {
                modalContent.classList.remove('opacity-0', 'scale-95');
                modalContent.classList.add('opacity-100', 'scale-100');
            }, 50);
        }
    
        function hideModal() {
            const modal = document.getElementById('crudModal');
            const modalContent = document.getElementById('crudModalContent');
    
            modalContent.classList.remove('opacity-100', 'scale-100');
            modalContent.classList.add('opacity-0', 'scale-95');
    
            setTimeout(() => {
                modal.classList.add('hidden');
            }, 150);
        }
    
        document.getElementById("cancelButton").addEventListener("click", hideModal);
        document.getElementById("closeModalBtn").addEventListener("click", hideModal);
    
        document.getElementById("ReviewEntryForm").addEventListener("submit", function(event) {
            event.preventDefault();
            addReviewEntry();
        });
    
        function addReviewEntry() {
            const csrfToken = document.querySelector('input[name="csrfmiddlewaretoken"]').value;
            const formData = new FormData(document.querySelector('#ReviewEntryForm'));
    
            fetch("{% url 'review:add_review_entry_ajax' %}", {
                method: "POST",
                headers: {
                    'X-CSRFToken': csrfToken,
                },
                body: formData,
            })
            .then(response => {
                if (response.ok) {
                    window.location.href = "{% url 'review:show_main' %}";
                } else {
                    console.log('Failed to submit review');
                }
            })
            .catch(error => console.log('Error:', error));
    
            document.getElementById("ReviewEntryForm").reset();
            hideModal();
    
            return false;
        }
    </script>    
</div>
{% endblock content %}